import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repository = 'https://github.com/skyboooox/KinopioHub';
const marker = '<!-- Generated by scripts/wiki.mjs; edit the source in the main repository. -->';
export const pages = Object.freeze({
  'docs/wiki-home.md': 'Home.md',
  'docs/wiki-home.en.md': 'Home-EN.md',
  'docs/wiki-sidebar.md': '_Sidebar.md',
  'docs/javascript.md': 'JavaScript.md',
  'docs/javascript.zh.md': 'JavaScript-ZH.md',
  'docs/python.md': 'Python.md',
  'docs/python.zh.md': 'Python-ZH.md',
  'docs/ros.md': 'ROS.md',
  'docs/ros.zh.md': 'ROS-ZH.md',
  'docs/cpp.md': 'Cpp.md',
  'docs/cpp.zh.md': 'Cpp-ZH.md',
  'docs/arduino.md': 'Arduino.md',
  'docs/arduino.zh.md': 'Arduino-ZH.md',
  'docs/web.md': 'Web.md',
  'docs/web.zh.md': 'Web-ZH.md',
  'docs/server.md': 'Server.md',
  'docs/server.zh.md': 'Server-ZH.md',
  'docs/architecture.md': 'Architecture.md',
  'docs/architecture.zh.md': 'Architecture-ZH.md',
  'docs/development.md': 'Development.md',
  'docs/development.zh.md': 'Development-ZH.md',
  'docs/variables.md': 'Variables.md',
  'docs/variables.zh.md': 'Variables-ZH.md',
  'docs/networking.md': 'Networking.md',
  'docs/networking.zh.md': 'Networking-ZH.md',
  'docs/troubleshooting.md': 'Troubleshooting.md',
  'docs/troubleshooting.zh.md': 'Troubleshooting-ZH.md',
  'docs/javascript-api.md': 'JavaScript-API.md',
  'docs/javascript-api.zh.md': 'JavaScript-API-ZH.md',
  'docs/python-api.md': 'Python-API.md',
  'docs/python-api.zh.md': 'Python-API-ZH.md',
  'docs/cpp-api.md': 'Cpp-API.md',
  'docs/cpp-api.zh.md': 'Cpp-API-ZH.md',
  'docs/arduino-api.md': 'Arduino-API.md',
  'docs/arduino-api.zh.md': 'Arduino-API-ZH.md',
  'docs/ros-config.md': 'ROS-Config.md',
  'docs/ros-config.zh.md': 'ROS-Config-ZH.md',
});
const retiredPages = ['Compatibility.md', 'Compatibility-ZH.md', 'Origins.md', 'Origins-ZH.md', 'Integration.md', 'Integration-ZH.md'];
const inside = (root, file) => file === root || file.startsWith(root + path.sep);
const urlPath = value => value.split('/').map(encodeURIComponent).join('/');

export async function renderPages(root) {
  root = await fs.realpath(root);
  const output = new Map();
  for (const [source, destination] of Object.entries(pages)) {
    const file = await fs.realpath(path.join(root, source));
    if (!inside(root, file)) throw new Error(`Source escapes repository: ${source}`);
    const markdown = await fs.readFile(file, 'utf8');
    const rewrite = async target => {
      if (!target || /^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i.test(target)) return target;
      const match = /^([^?#]*)([?#].*)?$/.exec(target);
      const suffix = match[2] ?? '';
      let relative;
      try { relative = decodeURIComponent(match[1]); } catch { throw new Error(`Invalid link in ${source}: ${target}`); }
      const absolute = path.resolve(root, path.dirname(source), relative);
      if (!inside(root, absolute)) throw new Error(`Link escapes repository in ${source}: ${target}`);
      let actual;
      try { actual = await fs.realpath(absolute); } catch { throw new Error(`Missing link target in ${source}: ${target}`); }
      if (!inside(root, actual)) throw new Error(`Link target escapes repository in ${source}: ${target}`);
      const local = path.relative(root, absolute).split(path.sep).join('/');
      return pages[local]
        ? `${repository}/wiki/${pages[local].slice(0, -3)}${suffix}`
        : `${repository}/blob/main/${urlPath(local)}${suffix}`;
    };
    const lines = markdown.split('\n');
    let fence;
    for (let i = 0; i < lines.length; i++) {
      const delimiter = /^ {0,3}(`{3,}|~{3,})/.exec(lines[i]);
      if (delimiter) {
        if (!fence) fence = delimiter[1];
        else if (delimiter[1][0] === fence[0] && delimiter[1].length >= fence.length && /^ {0,3}(?:`+|~+)\s*$/.test(lines[i])) fence = undefined;
        continue;
      }
      if (fence) continue;
      // Preserve inline code as well as fenced examples.
      const parts = lines[i].split(/(`+[^`]*`+)/g);
      for (let n = 0; n < parts.length; n += 2) {
        const pattern = /(\]\(\s*|^ {0,3}\[[^\]]+\]:\s*)(<[^>]*>|[^\s)]+)(?=\s|\)|$)/g;
        let result = '', cursor = 0;
        for (const match of parts[n].matchAll(pattern)) {
          const angled = match[2].startsWith('<');
          const target = angled ? match[2].slice(1, -1) : match[2];
          const replacement = await rewrite(target);
          result += parts[n].slice(cursor, match.index) + match[1] + (angled ? `<${replacement}>` : replacement);
          cursor = match.index + match[0].length;
        }
        parts[n] = result + parts[n].slice(cursor);
      }
      lines[i] = parts.join('');
    }
    output.set(destination, `${marker}\n\n${lines.join('\n').trimEnd()}\n`);
  }
  output.set('_Footer.md', `${marker}\n\n[首页](${repository}/wiki/Home) · [Home](${repository}/wiki/Home-EN) · [文档维护](${repository}/wiki/Development-ZH#github-wiki) · [Edit the docs](${repository}/wiki/Development#github-wiki)\n`);
  return output;
}

export async function run({ root, output = path.join(root, '.wiki'), check = false }) {
  const rendered = await renderPages(root);
  output = path.resolve(output);
  const retired = [];
  for (const name of retiredPages) {
    const target = path.join(output, name);
    try {
      const stat = await fs.lstat(target);
      if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Retired output is not a regular file: ${target}`);
      if (!(await fs.readFile(target, 'utf8')).startsWith(marker)) throw new Error(`Refusing to remove a non-generated file: ${target}`);
      if (check) throw new Error(`Retired Wiki page remains: ${name}; run build`);
      retired.push(target);
    } catch (error) { if (error.code !== 'ENOENT') throw error; }
  }
  // Validate all destinations before writing; never clean unrelated output files.
  for (const [name, content] of rendered) {
    const target = path.join(output, name);
    let existing;
    try {
      const stat = await fs.lstat(target);
      if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Output is not a regular file: ${target}`);
      existing = await fs.readFile(target, 'utf8');
    } catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (check && existing !== content) throw new Error(`Wiki output is missing or stale: ${name}; run build`);
    if (!check && existing !== undefined && !existing.startsWith(marker)) throw new Error(`Refusing to overwrite a non-generated file: ${target}`);
  }
  if (!check) {
    await fs.mkdir(output, { recursive: true });
    for (const [name, content] of rendered) await fs.writeFile(path.join(output, name), content);
    for (const target of retired) await fs.unlink(target);
  }
  return rendered.size;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2), command = args.shift() ?? 'build';
    if (!['build', 'check'].includes(command) || (args.length && (args.length !== 2 || args[0] !== '--output'))) throw new Error('Usage: node scripts/wiki.mjs [build|check] [--output PATH]');
    const root = fileURLToPath(new URL('../', import.meta.url));
    const count = await run({ root, ...(args.length ? { output: args[1] } : {}), check: command === 'check' });
    console.log(`Wiki ${command}: ${count} generated files verified.`);
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
